easy_admin:
    entities:
        Order:
            class: '%mtt_order.order_entity_alias%'
            list:
                fields: ['id', 'status', 'createdAt']
            form:
                fields: ['status', 'items']

        OrderStatus:
            class: '%mtt_order.order_status_entity_alias%'
            list:
                fields: ['id', 'name', 'statusIdErp', 'defaultStatus']
            form:
                fields: ['name', 'statusIdErp', 'defaultStatus']